tab enuretic beenbullied, row chi2
tab enuretic mooddisorder, row chi2
tab enuretic putatdepressIV, row chi2
tab enuretic estmoodIV, row chi2
tab enuretic putatdepressV, row chi2
tab enuretic estmoodV, row chi2
tab enuretic disorderedsleep, row chi2
tab enuretic sleepdepriv, row chi2
tab enuretic constipated, row chi2
tab enuretic cupsbefore7, row chi2
tab enuretic cupsafter7, row chi2
